// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClr020o3a3DcIThKRtt2n8KZe9cVdEGss',
    appId: '1:883553815404:web:14e509ac28c2196bc1c149',
    messagingSenderId: '883553815404',
    projectId: 'gestaoescalas',
    authDomain: 'gestaoescalas.firebaseapp.com',
    storageBucket: 'gestaoescalas.firebasestorage.app',
    measurementId: 'G-4N8NK6930C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscCr35wKF8OGaAeUiqM_OhK2wTFGSPbg',
    appId: '1:883553815404:android:37c6c80d2d4a670fc1c149',
    messagingSenderId: '883553815404',
    projectId: 'gestaoescalas',
    storageBucket: 'gestaoescalas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5hu2SdbHeVuAbPgmIooBkzQq-DeZuXU',
    appId: '1:883553815404:ios:585c9b5d2ffb296ec1c149',
    messagingSenderId: '883553815404',
    projectId: 'gestaoescalas',
    storageBucket: 'gestaoescalas.firebasestorage.app',
    iosBundleId: 'com.example.gestaoLeitores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg5hu2SdbHeVuAbPgmIooBkzQq-DeZuXU',
    appId: '1:883553815404:ios:585c9b5d2ffb296ec1c149',
    messagingSenderId: '883553815404',
    projectId: 'gestaoescalas',
    storageBucket: 'gestaoescalas.firebasestorage.app',
    iosBundleId: 'com.example.gestaoLeitores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClr020o3a3DcIThKRtt2n8KZe9cVdEGss',
    appId: '1:883553815404:web:ada549a55b917ac5c1c149',
    messagingSenderId: '883553815404',
    projectId: 'gestaoescalas',
    authDomain: 'gestaoescalas.firebaseapp.com',
    storageBucket: 'gestaoescalas.firebasestorage.app',
    measurementId: 'G-HDSKF8LHJD',
  );
}
